server:
  port: 9000

spring:
  application:
    name: apigateway-service
  cloud:
    config:
      uri: http://localhost:8888
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    gateway:
      routes:
        - id: repository-service
          uri: lb://REPOSITORY-SERVICE
          predicates:
            - Path=/repository-service/**
          filters:
            - RewritePath=/repository-service/(?<segment>.*), /$\{segment}
        - id: repository-service
          uri: lb://REPOSITORY-SERVICE
          predicates:
            - Path=/repository-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/repository-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, busrefresh, info